### ISSUE TITLE
TC001 Special Commands

### ISSUE THREAD

**Issue by kchiwhane** [92es/Thermal-Camera-Redux#1]
@92es 

In Les' Lab's original video covering the PyThermalcam repo (https://www.youtube.com/watch?v=PiVwZoQ8_jQ), Les states @8:50 that "[the code] doesnt' send any of the special commands to the camera itself. It just receives raw data...".

Does this mean there are special commands associated with the TC001 that any dev has access to?

**Comment by 92es** [comment]
> @92es
> 
> In Les' Lab's original video covering the PyThermalcam repo (https://www.youtube.com/watch?v=PiVwZoQ8_jQ), Les states @8:50 that "[the code] doesnt' send any of the special commands to the camera itself. It just receives raw data...".
> 
> Does this mean there are special commands associated with the TC001 that any dev has access to?

The TC001 has video out and has proprietary commands over the USB protocol.  

Both Les's original Python script and this C/C++ app use just the video out.

I have requested the USB command spec from Topdon, but the request has fallen on deaf ears.

The ability to set emissivity values (and a couple of other settings)  would be useful, but I don't want to brick any cameras via experimentation.

All of the features in this app is done externally in software after reading the raw data from the camera.  This app has more features than their OEM apps, sans a couple of internal camera settings.

Some other people have tried to reverse engineer some of the USB commands, but I have not experimented with their discoveries.

Hope this answers your questions.
